### ISSUE TITLE
В версии 2.0 при экспорте, когда поле пустое возникает ошибка

### ISSUE THREAD

**Issue by Mostok** [visual-ideas/moonshine-spatie-medialibrary#5]
Когда экспортирую, в режиме одного файла, и этого самого файла нет возникает ошибка
`VI\MoonShineSpatieMediaLibrary\Fields\MediaLibrary::resolvePreview(): Return value must be of type Illuminate\Contracts\View\View|string, null returned`

Предлагаемое решение в этом самом файле строка 34 заменить на `: ($this->value?->getFullUrl() ?? '');`

**Comment by alexvenga** [comment]
Добавил в версии https://github.com/visual-ideas/moonshine-spatie-medialibrary/releases/tag/2.0.4
